/**
 * Seed: 40 competitive products (TheSynLab v2.0).
 * Covers AI Workflow / Productivity, Smart Home, and Office Hardware hubs.
 * Each product ships with novaTrustScores and novaIntegrationScores.
 */

import { mutation } from "./_generated/server";

// ---------------------------------------------------------------------------
// Helper types
// ---------------------------------------------------------------------------
interface ProductSeed {
  productName: string;
  productSlug: string;
  productType: string;
  hub: string;
  category: string;
  subcategory: string;
  manufacturer: string;
  description: string;
  price: number;
  priceCurrency: string;
  priceModel: string;
  status: string;
  isSponsored: boolean;
  sponsorDisclosed: boolean;
  overallScore: number;
  verdictSummary: string;
  features: Record<string, unknown>;
  specifications: Record<string, unknown>;
  officialWebsite: string;
  documentationUrl: string;
  featuredImageUrl: string;
}

interface TrustSeed {
  version: number;
  totalScore: number;
  dataPrivacyPractices: number;
  encryptionStandards: number;
  termsTransparency: number;
  ethicalAiTransparency: number;
  thirdPartyAudits: number;
  testedBy: string;
  testedDate: number;
  isCurrent: boolean;
  isVerified: boolean;
  createdBy: string;
}

interface IntegrationSeed {
  version: number;
  totalScore: number;
  apiDocumentation: number;
  crossPlatform: number;
  smartHomeEcosystems: number;
  automationPlatforms: number;
  developerCommunity: number;
  testedBy: string;
  testedDate: number;
  isCurrent: boolean;
  isVerified: boolean;
  createdBy: string;
}

const NOW = Date.now();
const TESTER = "synlab-editorial-team";
const CREATOR = "system_admin";

// ---------------------------------------------------------------------------
// Unsplash image helpers
// ---------------------------------------------------------------------------
const IMG = {
  software_productivity: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=600&fit=crop",
  software_workspace: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
  software_automation: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
  software_crm: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
  software_writing: "https://images.unsplash.com/photo-1468779036391-52341f60b55d?w=800&h=600&fit=crop",
  software_helpdesk: "https://images.unsplash.com/photo-1553775282-20af80779df7?w=800&h=600&fit=crop",
  hardware_speaker: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&h=600&fit=crop",
  hardware_lock: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
  hardware_camera: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&h=600&fit=crop",
  hardware_router: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&h=600&fit=crop",
  hardware_thermostat: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&h=600&fit=crop",
  hardware_lighting: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=600&fit=crop",
  hardware_plug: "https://images.unsplash.com/photo-1558346547-4439467bd1d5?w=800&h=600&fit=crop",
  hardware_vacuum: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
  hardware_doorbell: "https://images.unsplash.com/photo-1555963966-b7ae5404b6e8?w=800&h=600&fit=crop",
  hardware_sensor: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop",
  hardware_monitor: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=600&fit=crop",
  hardware_keyboard: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=600&fit=crop",
  hardware_printer: "https://images.unsplash.com/photo-1612198273627-e6e6d3d7f5e0?w=800&h=600&fit=crop",
  hardware_webcam: "https://images.unsplash.com/photo-1626285861696-9f0bf5a49c6d?w=800&h=600&fit=crop",
  hardware_headset: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop",
  hardware_dock: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=800&h=600&fit=crop",
  hardware_chair: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&h=600&fit=crop",
  hardware_nas: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop",
  hardware_conference: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=600&fit=crop",
  hardware_label: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop",
  hardware_desk: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&h=600&fit=crop",
  hardware_mouse: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&h=600&fit=crop",
};

// ---------------------------------------------------------------------------
// Product catalogue – 40 entries
// ---------------------------------------------------------------------------
const products: ProductSeed[] = [
  // ====== AI WORKFLOW / PRODUCTIVITY ======
  {
    productName: "FocusFlow Pro",
    productSlug: "focusflow-pro",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Focus Apps",
    manufacturer: "FocusFlow Inc.",
    description: "A time-blocking and Pomodoro app with deep focus analytics, session tracking, and verified usage data for Trust Score computation.",
    price: 9.99,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 87.4,
    verdictSummary: "Best-in-class focus timer with strong privacy defaults and excellent calendar integrations.",
    features: { pomodoroTimer: true, timeBlocking: true, analyticsExport: true, calendarSync: true },
    specifications: { platforms: ["Web", "iOS", "Android", "macOS"], offlineMode: true, dataExport: "CSV, JSON" },
    officialWebsite: "https://focusflow.app",
    documentationUrl: "https://docs.focusflow.app",
    featuredImageUrl: IMG.software_productivity,
  },
  {
    productName: "Google Workspace Business Starter",
    productSlug: "google-workspace-business-starter",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Cloud Office",
    manufacturer: "Google LLC",
    description: "Google's cloud office suite with Gmail, Docs, Drive, Meet, and admin controls reviewed for uptime, security certifications, and CRM integrations.",
    price: 6.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 91.2,
    verdictSummary: "Dominant cloud office suite with near-flawless integration coverage but privacy trade-offs to consider.",
    features: { email: true, videoConferencing: true, cloudStorage: "30GB", adminConsole: true },
    specifications: { uptime: "99.9%", iso27001: true, gdprCompliant: true },
    officialWebsite: "https://workspace.google.com",
    documentationUrl: "https://support.google.com/a",
    featuredImageUrl: IMG.software_workspace,
  },
  {
    productName: "Notion Team Plan",
    productSlug: "notion-team-plan",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Project OS",
    manufacturer: "Notion Labs Inc.",
    description: "All-in-one workspace reviewed for roadmap transparency, exportability, data residency options, and API integration depth.",
    price: 10.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 88.5,
    verdictSummary: "Incredibly flexible workspace with a growing API but limited enterprise data residency options.",
    features: { databases: true, aiWriting: true, guestAccess: true, versionHistory: true },
    specifications: { exportFormats: ["Markdown", "CSV", "PDF"], apiAvailable: true },
    officialWebsite: "https://notion.so",
    documentationUrl: "https://developers.notion.com",
    featuredImageUrl: IMG.software_workspace,
  },
  {
    productName: "GitHub Enterprise",
    productSlug: "github-enterprise",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Developer Tools",
    manufacturer: "GitHub Inc.",
    description: "Enterprise code hosting platform reviewed for security posture, SAML SSO, reliability, and CI/CD integration coverage.",
    price: 21.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 93.1,
    verdictSummary: "Gold standard for developer collaboration with deep ecosystem integrations and robust audit logging.",
    features: { codeReview: true, actions: true, advancedSecurity: true, samlSSO: true },
    specifications: { uptime: "99.95%", soc2Type2: true },
    officialWebsite: "https://github.com/enterprise",
    documentationUrl: "https://docs.github.com/en/enterprise-cloud@latest",
    featuredImageUrl: IMG.software_automation,
  },
  {
    productName: "HubSpot CRM",
    productSlug: "hubspot-crm",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "CRM",
    manufacturer: "HubSpot Inc.",
    description: "CRM platform reviewed for data integrity, permission controls, vendor lock-in risk, and email/billing tool integrations.",
    price: 0,
    priceCurrency: "USD",
    priceModel: "freemium",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 86.7,
    verdictSummary: "Best free CRM entry point with strong integrations, but data export limits escalate with paid tiers.",
    features: { contactManagement: true, dealPipeline: true, emailTracking: true, reportingDashboard: true },
    specifications: { freeTierContacts: "Unlimited", apiAccess: true, gdprTools: true },
    officialWebsite: "https://hubspot.com/crm",
    documentationUrl: "https://developers.hubspot.com",
    featuredImageUrl: IMG.software_crm,
  },
  {
    productName: "Miro Business",
    productSlug: "miro-business",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Collaboration",
    manufacturer: "RealtimeBoard Inc. (Miro)",
    description: "Online whiteboard reviewed for real-time reliability in large workshops, content ownership policies, and calendar/video integrations.",
    price: 16.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 85.9,
    verdictSummary: "Leading collaboration canvas with excellent video platform integrations and solid uptime track record.",
    features: { infiniteCanvas: true, aiDiagramming: true, videoCallEmbed: true, templateLibrary: true },
    specifications: { maxBoardSize: "Unlimited", guestViewing: true },
    officialWebsite: "https://miro.com",
    documentationUrl: "https://developers.miro.com",
    featuredImageUrl: IMG.software_workspace,
  },
  {
    productName: "Zapier Professional",
    productSlug: "zapier-professional",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Automation",
    manufacturer: "Zapier Inc.",
    description: "Workflow automation platform reviewed for execution reliability, incident history, connector coverage, and extensibility via custom code steps.",
    price: 49.99,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 89.3,
    verdictSummary: "Largest connector library in the automation space with solid reliability, though pricing scales steeply.",
    features: { multiStepZaps: true, codeSteps: true, paths: true, scheduleTriggered: true },
    specifications: { appConnections: "6000+", taskHistory: "30 days" },
    officialWebsite: "https://zapier.com",
    documentationUrl: "https://zapier.com/developer-platform",
    featuredImageUrl: IMG.software_automation,
  },
  {
    productName: "Zendesk Suite",
    productSlug: "zendesk-suite",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Knowledge Base",
    manufacturer: "Zendesk Inc.",
    description: "Helpdesk and knowledge base platform reviewed for SLAs, backup policies, migration options, and chat/email/analytics integrations.",
    price: 55.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 87.8,
    verdictSummary: "Enterprise-grade support platform with deep integration coverage and transparent SLA commitments.",
    features: { ticketingSystem: true, aiAnswerBot: true, multiChannel: true, customReporting: true },
    specifications: { sla: "99.9% uptime", dataResidency: ["US", "EU"] },
    officialWebsite: "https://zendesk.com",
    documentationUrl: "https://developer.zendesk.com",
    featuredImageUrl: IMG.software_helpdesk,
  },
  {
    productName: "Todoist Business",
    productSlug: "todoist-business",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Task Manager",
    manufacturer: "Doist Inc.",
    description: "Personal and team task manager reviewed for privacy practices, data export quality, business model transparency, and calendar/voice integrations.",
    price: 6.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 84.2,
    verdictSummary: "Clean, privacy-respecting task manager with strong natural language input and good cross-platform sync.",
    features: { naturalLanguageInput: true, teamInbox: true, googleCalendarSync: true, activityLog: true },
    specifications: { platforms: ["Web", "iOS", "Android", "macOS", "Windows"], offlineSync: true },
    officialWebsite: "https://todoist.com",
    documentationUrl: "https://developer.todoist.com",
    featuredImageUrl: IMG.software_productivity,
  },
  {
    productName: "Grammarly Business",
    productSlug: "grammarly-business",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "AI Copilot",
    manufacturer: "Grammarly Inc.",
    description: "AI writing assistant reviewed for model transparency, data usage policies, safety controls, and browser/docs/IDE integrations.",
    price: 15.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 83.6,
    verdictSummary: "Mature AI writing tool with wide integration surface but data training practices warrant scrutiny.",
    features: { toneDetection: true, plagiarismCheck: true, brandVoice: true, analyticsDashboard: true },
    specifications: { browserExtensions: ["Chrome", "Firefox", "Safari", "Edge"], officeIntegration: ["Word", "Google Docs", "Outlook"] },
    officialWebsite: "https://grammarly.com/business",
    documentationUrl: "https://developer.grammarly.com",
    featuredImageUrl: IMG.software_writing,
  },
  {
    productName: "Microsoft 365 Business Standard",
    productSlug: "microsoft-365-business-standard",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Cloud Office",
    manufacturer: "Microsoft",
    description: "Comprehensive cloud office suite with desktop apps reviewed for admin controls, compliance certifications, and Teams/SharePoint integrations.",
    price: 12.50,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 90.1,
    verdictSummary: "The enterprise-grade choice for regulated industries—unmatched compliance tooling and deepest Windows ecosystem integration.",
    features: { desktopApps: true, teamsIncluded: true, oneDriveTB: true, advancedCompliance: true },
    specifications: { uptime: "99.9%", iso27001: true, hipaaCompliant: true, dataResidency: ["US", "EU", "APAC"] },
    officialWebsite: "https://microsoft.com/microsoft-365",
    documentationUrl: "https://learn.microsoft.com/microsoft-365",
    featuredImageUrl: IMG.software_workspace,
  },
  {
    productName: "Make Core",
    productSlug: "make-core",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Automation",
    manufacturer: "Celonis SE (Make)",
    description: "Visual automation platform reviewed for scenario reliability, error handling, connector depth, and extensibility with webhooks and custom apps.",
    price: 10.59,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 87.6,
    verdictSummary: "Best visual-flow automation tool with superior scenario branching and granular error control compared to Zapier.",
    features: { visualBuilder: true, errorHandling: true, webhooks: true, dataStores: true },
    specifications: { appConnections: "1900+", operationsPerMonth: 10000, executionHistory: "30 days" },
    officialWebsite: "https://make.com",
    documentationUrl: "https://developers.make.com",
    featuredImageUrl: IMG.software_automation,
  },
  {
    productName: "ClickUp Business",
    productSlug: "clickup-business",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Project OS",
    manufacturer: "ClickUp",
    description: "All-in-one project management workspace reviewed for roadmap transparency, API depth, automation tools, and data export options.",
    price: 12.00,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 85.4,
    verdictSummary: "Most feature-dense project OS on the market, though its breadth introduces complexity that smaller teams may not need.",
    features: { customFields: true, nativeDocs: true, goalTracking: true, timeTracking: true },
    specifications: { views: ["List", "Board", "Gantt", "Calendar", "Map", "Workload"], apiAvailable: true },
    officialWebsite: "https://clickup.com",
    documentationUrl: "https://developer.clickup.com",
    featuredImageUrl: IMG.software_productivity,
  },
  {
    productName: "n8n Community Edition",
    productSlug: "n8n-community-edition",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Automation",
    manufacturer: "n8n GmbH",
    description: "Open-source workflow automation platform reviewed for self-hosted reliability, connector extensibility, and code node flexibility.",
    price: 0,
    priceCurrency: "USD",
    priceModel: "freemium",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 85.8,
    verdictSummary: "Most developer-friendly automation tool—self-hostable, with code nodes and the best custom integration flexibility available.",
    features: { selfHosted: true, codeNodes: true, gitVersioning: true, subWorkflows: true },
    specifications: { appConnections: "400+", licenseType: "Sustainable Use License", deploymentOptions: ["Self-hosted", "Cloud"] },
    officialWebsite: "https://n8n.io",
    documentationUrl: "https://docs.n8n.io",
    featuredImageUrl: IMG.software_automation,
  },
  {
    productName: "Atlassian Confluence Cloud",
    productSlug: "atlassian-confluence-cloud",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Knowledge Base",
    manufacturer: "Atlassian",
    description: "Team knowledge base reviewed for SLA reliability, admin backup controls, migration path quality, and Jira/Slack/analytics integrations.",
    price: 5.75,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 84.1,
    verdictSummary: "Best knowledge base for Jira-centric teams with deep bidirectional linking, though complex permission models are a pain point.",
    features: { jiraIntegration: true, pageTemplates: true, aiSummarization: true, spacePermissions: true },
    specifications: { uptime: "99.9%", dataResidency: ["US", "EU", "AU"] },
    officialWebsite: "https://atlassian.com/confluence",
    documentationUrl: "https://developer.atlassian.com/confluence",
    featuredImageUrl: IMG.software_helpdesk,
  },
  {
    productName: "Asana Business",
    productSlug: "asana-business",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "Project OS",
    manufacturer: "Asana Inc.",
    description: "Project management platform reviewed for workflow rules, portfolio management, API reliability, and calendar/CRM integrations.",
    price: 24.99,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 86.3,
    verdictSummary: "Superior for cross-team dependency management with strong automation rules and a class-leading mobile experience.",
    features: { portfolios: true, workloadBalancing: true, customRules: true, approvals: true },
    specifications: { views: ["List", "Board", "Timeline", "Calendar"], apiAvailable: true, ssoSaml: true },
    officialWebsite: "https://asana.com",
    documentationUrl: "https://developers.asana.com",
    featuredImageUrl: IMG.software_crm,
  },
  {
    productName: "Pipedrive CRM",
    productSlug: "pipedrive-crm",
    productType: "software",
    hub: "ai_workflow",
    category: "Productivity Software",
    subcategory: "CRM",
    manufacturer: "Pipedrive OÜ",
    description: "Sales-focused CRM reviewed for pipeline data integrity, permissioning models, lock-in risk, and email/lead-scoring/billing integrations.",
    price: 24.90,
    priceCurrency: "USD",
    priceModel: "subscription",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 83.9,
    verdictSummary: "Sales reps' favourite CRM for its visual pipeline, though enterprise admin controls lag behind HubSpot and Salesforce.",
    features: { visualPipeline: true, emailTracking: true, leadScoring: true, salesForecasting: true },
    specifications: { exportFormats: ["CSV", "Excel"], apiAvailable: true, gdprCompliant: true },
    officialWebsite: "https://pipedrive.com",
    documentationUrl: "https://developers.pipedrive.com",
    featuredImageUrl: IMG.software_crm,
  },

  // ====== INTELLIGENT HOME / SMART HOME ======
  {
    productName: "Amazon Echo Hub",
    productSlug: "amazon-echo-hub",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Speaker",
    manufacturer: "Amazon",
    description: "Smart display and home control panel reviewed for privacy defaults, mic mute controls, update cadence, and multi-room/ecosystem integration.",
    price: 179.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 82.1,
    verdictSummary: "Central smart home controller with broad Alexa ecosystem depth; physical mic off button adds trust.",
    features: { touchscreen: true, micMuteButton: true, zigbeeHub: true, matterSupport: true },
    specifications: { screenSize: "8 inch", wifiStandard: "Wi-Fi 6", bluetooth: "5.0" },
    officialWebsite: "https://amazon.com/echo-hub",
    documentationUrl: "https://developer.amazon.com/alexa",
    featuredImageUrl: IMG.hardware_speaker,
  },
  {
    productName: "Schlage Encode Plus",
    productSlug: "schlage-encode-plus",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Lock",
    manufacturer: "Schlage",
    description: "Smart door lock reviewed for AES encryption, offline access fallback, failure modes, and voice assistant/alarm system integrations.",
    price: 299.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 91.0,
    verdictSummary: "Premium smart lock with built-in Apple Home Key and strong offline failover using keypad and physical key.",
    features: { appleHomeKey: true, builtInWifi: true, fingerprintReader: false, offlineKeypad: true },
    specifications: { encryption: "AES-128", batteryLife: "6 months", matterReady: true },
    officialWebsite: "https://schlage.com/encode-plus",
    documentationUrl: "https://schlage.com/support",
    featuredImageUrl: IMG.hardware_lock,
  },
  {
    productName: "Arlo Pro 5S",
    productSlug: "arlo-pro-5s",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Security Camera",
    manufacturer: "Arlo Technologies",
    description: "Outdoor security camera reviewed for uptime, video retention controls, local storage options, and smart display/NVR integrations.",
    price: 249.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 88.4,
    verdictSummary: "Top-tier outdoor camera with color night vision and flexible local + cloud storage—rare in its class.",
    features: { colorNightVision: true, localStorageUSB: true, spotlightLight: true, twoWayAudio: true },
    specifications: { resolution: "2K HDR", fieldOfView: "160°", weatherRating: "IP67" },
    officialWebsite: "https://arlo.com/pro-5s",
    documentationUrl: "https://developer.arlo.com",
    featuredImageUrl: IMG.hardware_camera,
  },
  {
    productName: "Eero Max 7",
    productSlug: "eero-max-7",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Mesh Router",
    manufacturer: "Amazon (eero)",
    description: "Tri-band mesh Wi-Fi system reviewed for security update cadence, parental controls, IoT protocol support, and ISP compatibility.",
    price: 599.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 90.5,
    verdictSummary: "Fastest consumer mesh system with automatic security updates and strong parental control features.",
    features: { wifi7: true, automaticUpdates: true, eeroSecurePlus: true, threadBorderRouter: true },
    specifications: { maxSpeed: "9.4 Gbps", wiredPorts: 2, matterSupport: true },
    officialWebsite: "https://eero.com/max7",
    documentationUrl: "https://developer.amazon.com/eero",
    featuredImageUrl: IMG.hardware_router,
  },
  {
    productName: "Ecobee Smart Thermostat Premium",
    productSlug: "ecobee-smart-thermostat-premium",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Thermostat",
    manufacturer: "Ecobee",
    description: "Connected thermostat reviewed for sensor reliability, long-term firmware support, HVAC brand compatibility, and smart platform integrations.",
    price: 249.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 92.3,
    verdictSummary: "Best overall smart thermostat with room sensors, built-in Alexa, and the strongest privacy record in its category.",
    features: { roomSensors: true, builtInAlexa: true, smartRecovery: true, energyReports: true },
    specifications: { compatibility: ["24V systems", "Heat pump"], matterCertified: true, displaySize: "3.5 inch" },
    officialWebsite: "https://ecobee.com",
    documentationUrl: "https://developer.ecobee.com",
    featuredImageUrl: IMG.hardware_thermostat,
  },
  {
    productName: "Philips Hue Starter Kit",
    productSlug: "philips-hue-starter-kit",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Lighting",
    manufacturer: "Signify",
    description: "Smart bulb and hub ecosystem reviewed for connectivity stability, long-term app support, and Zigbee/Matter/Thread compatibility.",
    price: 99.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 89.7,
    verdictSummary: "Most mature smart lighting ecosystem with exceptional color accuracy and a future-proof Matter bridge.",
    features: { sixteenMillionColors: true, matterBridge: true, entertainmentSync: true, gradientBulbs: true },
    specifications: { protocol: "Zigbee + Matter", maxBrightness: "1100 lm", bulbsIncluded: 3 },
    officialWebsite: "https://philips-hue.com",
    documentationUrl: "https://developers.meethue.com",
    featuredImageUrl: IMG.hardware_lighting,
  },
  {
    productName: "Kasa Smart Plug EP25",
    productSlug: "kasa-smart-plug-ep25",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Plug",
    manufacturer: "TP-Link (Kasa)",
    description: "Smart plug with energy monitoring reviewed for switching reliability, overload protection, and voice platform/dashboard integrations.",
    price: 17.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 81.4,
    verdictSummary: "Best value energy-monitoring plug with reliable scheduling and strong Alexa/Google Home support.",
    features: { energyMonitoring: true, overloadProtection: true, awayMode: true, schedules: true },
    specifications: { maxLoad: "15A / 1800W", protocol: "Wi-Fi", matterSupport: false },
    officialWebsite: "https://kasasmart.com",
    documentationUrl: "https://developer.tp-link.com",
    featuredImageUrl: IMG.hardware_plug,
  },
  {
    productName: "Roborock S8 Pro Ultra",
    productSlug: "roborock-s8-pro-ultra",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Robot Vacuum",
    manufacturer: "Roborock",
    description: "Robot vacuum and mop reviewed for navigation accuracy, mapping data privacy, repairability score, and voice/cleaning routine integrations.",
    price: 1599.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 94.1,
    verdictSummary: "The pinnacle of autonomous floor care—self-emptying, self-washing, and self-refilling with exceptional mapping.",
    features: { selfEmptying: true, selfWashing: true, sonicMopping: true, threeMapping: true },
    specifications: { suction: "6000 Pa", noGoZones: true, floorDetection: true },
    officialWebsite: "https://roborock.com/s8-pro-ultra",
    documentationUrl: "https://developer.roborock.com",
    featuredImageUrl: IMG.hardware_vacuum,
  },
  {
    productName: "Google Nest Doorbell (Wired)",
    productSlug: "google-nest-doorbell-wired",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Doorbell",
    manufacturer: "Google",
    description: "Smart doorbell reviewed for motion detection reliability, end-to-end encryption, local storage options, and lock/hub/display integrations.",
    price: 179.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 85.3,
    verdictSummary: "Polished smart doorbell with HDR video and tight Google Home integration, though cloud dependency remains high.",
    features: { hdrVideo: true, packageDetection: true, continuousRecording: true, facialRecognition: true },
    specifications: { resolution: "1080p HDR", fieldOfView: "145°", matterSupport: false },
    officialWebsite: "https://store.google.com/nest-doorbell",
    documentationUrl: "https://developers.home.google.com",
    featuredImageUrl: IMG.hardware_doorbell,
  },
  {
    productName: "Aqara Multi-Sensor Kit",
    productSlug: "aqara-multi-sensor-kit",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Multi-Sensor",
    manufacturer: "Aqara",
    description: "Motion, contact, temperature, and humidity sensors reviewed for battery life, false-positive rates, and hub/automation rules integrations.",
    price: 79.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 86.9,
    verdictSummary: "Exceptional value multi-sensor bundle with Zigbee reliability and broad HomeKit/Matter/Google Home support.",
    features: { motionSensor: true, doorWindowContact: true, temperatureHumidity: true, vibrationSensor: true },
    specifications: { protocol: "Zigbee 3.0 + Matter", batteryLife: "2 years", hubRequired: false },
    officialWebsite: "https://aqara.com",
    documentationUrl: "https://developer.aqara.com",
    featuredImageUrl: IMG.hardware_sensor,
  },
  {
    productName: "Google Nest Thermostat",
    productSlug: "google-nest-thermostat",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Thermostat",
    manufacturer: "Google",
    description: "Entry-level smart thermostat reviewed for sensor reliability, Google Home integration depth, and schedule learning capabilities.",
    price: 129.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 80.6,
    verdictSummary: "Great value starter thermostat with clean design and Savings Finder, but lacks remote sensors found on premium rivals.",
    features: { savingsFinder: true, googleAssistant: true, scheduleAdaptation: true, energyHistory: true },
    specifications: { compatibility: "Most 24V systems", displayType: "Mirror", matterReady: false },
    officialWebsite: "https://store.google.com/nest-thermostat",
    documentationUrl: "https://developers.home.google.com",
    featuredImageUrl: IMG.hardware_thermostat,
  },
  {
    productName: "Ring Video Doorbell Pro 2",
    productSlug: "ring-video-doorbell-pro-2",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Doorbell",
    manufacturer: "Ring (Amazon)",
    description: "Wired smart doorbell with 3D motion detection reviewed for encryption practices, local storage options, and Alexa ecosystem integration.",
    price: 249.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 82.7,
    verdictSummary: "Strong video quality and 3D motion zones, but law enforcement data-sharing history keeps the Trust Score from climbing higher.",
    features: { threeDMotionDetection: true, headToToeVideo: true, colorNightVision: true },
    specifications: { resolution: "1536p HD", fieldOfView: "150°x150°", localStorageOption: false },
    officialWebsite: "https://ring.com/doorbell-pro-2",
    documentationUrl: "https://developer.amazon.com/ring",
    featuredImageUrl: IMG.hardware_doorbell,
  },
  {
    productName: "TP-Link Tapo L930 LED Strip",
    productSlug: "tp-link-tapo-l930",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Lighting",
    manufacturer: "TP-Link (Tapo)",
    description: "Multi-color addressable LED light strip reviewed for connectivity stability, music sync reliability, and Matter/voice ecosystem integration.",
    price: 39.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 77.5,
    verdictSummary: "Best value addressable strip light with music sync and Matter support—minor app stability issues hold back the score.",
    features: { addressableZones: true, musicSync: true, matterCertified: true, voiceControl: true },
    specifications: { length: "5 meters", zones: 50, maxBrightness: "2000 lm" },
    officialWebsite: "https://tp-link.com/tapo-l930",
    documentationUrl: "https://developer.tp-link.com",
    featuredImageUrl: IMG.hardware_lighting,
  },
  {
    productName: "Lutron Caseta Smart Switch",
    productSlug: "lutron-caseta-smart-switch",
    productType: "hardware",
    hub: "intelligent_home",
    category: "Smart Home",
    subcategory: "Smart Lighting",
    manufacturer: "Lutron Electronics",
    description: "In-wall smart dimmer switch reviewed for RF connectivity stability, neutral-wire-free installation, and Apple Home/Alexa/Google integration.",
    price: 59.95,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 91.5,
    verdictSummary: "Most reliable smart switch on the market—Lutron's Clear Connect RF protocol has a near-flawless 10-year track record.",
    features: { noNeutralWire: true, clearConnectRF: true, appleHomeKit: true },
    specifications: { protocol: "Clear Connect RF + Bridge", compatibility: "Most dimmable LEDs" },
    officialWebsite: "https://lutron.com/caseta",
    documentationUrl: "https://developer.lutron.com",
    featuredImageUrl: IMG.hardware_lighting,
  },

  // ====== HYBRID OFFICE / OFFICE HARDWARE ======
  {
    productName: "Dell UltraSharp U3223QE",
    productSlug: "dell-ultrasharp-u3223qe",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Monitor & Dock",
    manufacturer: "Dell",
    description: "4K USB-C monitor with built-in KVM and Ethernet reviewed for panel consistency, warranty terms, and multi-OS docking integration.",
    price: 999.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 92.6,
    verdictSummary: "Best professional monitor for single-cable docking workflows with class-leading color accuracy and IPS Black panel.",
    features: { usbCDocking: true, builtInKVM: true, ethernetPort: true, ergonomicStand: true },
    specifications: { resolution: "3840x2160", panelType: "IPS Black", refreshRate: "60Hz", usbCPower: "90W" },
    officialWebsite: "https://dell.com/u3223qe",
    documentationUrl: "https://dell.com/support",
    featuredImageUrl: IMG.hardware_monitor,
  },
  {
    productName: "Keychron Q1 Pro",
    productSlug: "keychron-q1-pro",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Keyboard & Mouse",
    manufacturer: "Keychron",
    description: "Mechanical keyboard reviewed for switch longevity, RMA rates, Bluetooth multi-device pairing, and OS-level feature integration.",
    price: 199.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 90.8,
    verdictSummary: "Premium gasket-mount keyboard with wireless versatility and open-source QMK/VIA firmware for deep customization.",
    features: { qmkVia: true, bluetoothMultiDevice: true, hotSwappable: true, rgbBacklight: true },
    specifications: { layout: "75%", connectivity: "Bluetooth 5.1 + USB-C" },
    officialWebsite: "https://keychron.com/q1-pro",
    documentationUrl: "https://github.com/Keychron",
    featuredImageUrl: IMG.hardware_keyboard,
  },
  {
    productName: "Brother MFC-L3760CDW",
    productSlug: "brother-mfc-l3760cdw",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Printer & Scanner",
    manufacturer: "Brother",
    description: "Color laser all-in-one reviewed for duty-cycle reliability, driver support longevity, cloud print, and document app integrations.",
    price: 449.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 84.7,
    verdictSummary: "Reliable mid-range color laser with low per-page costs and dependable long-term driver support from Brother.",
    features: { colorLaser: true, duplex: true, adfScanner: true, cloudPrint: true },
    specifications: { printSpeed: "25 ppm", monthlyDutyCycle: "30000 pages", connectivity: ["Wi-Fi", "Ethernet", "USB"] },
    officialWebsite: "https://brother.com/mfc-l3760cdw",
    documentationUrl: "https://support.brother.com",
    featuredImageUrl: IMG.hardware_printer,
  },
  {
    productName: "Logitech Brio 4K",
    productSlug: "logitech-brio-4k",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Webcam & Conferencing",
    manufacturer: "Logitech",
    description: "4K business webcam reviewed for firmware update cadence, low-light performance, and integration with major video conferencing platforms.",
    price: 199.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 88.2,
    verdictSummary: "Top webcam for executives needing 4K recording and Windows Hello facial recognition in a single device.",
    features: { fourKVideo: true, hdrSupport: true, windowsHello: true, privacyShutter: true },
    specifications: { resolution: "4096x2160", fieldOfView: "65°/78°/90°", frameRate: "30fps at 4K" },
    officialWebsite: "https://logitech.com/brio",
    documentationUrl: "https://support.logitech.com",
    featuredImageUrl: IMG.hardware_webcam,
  },
  {
    productName: "Jabra Evolve2 85",
    productSlug: "jabra-evolve2-85",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Headset & Mic",
    manufacturer: "Jabra (GN Audio)",
    description: "Wireless ANC headset reviewed for build quality, all-day comfort, UC certifications, and multi-device switching.",
    price: 449.00,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 93.5,
    verdictSummary: "Best professional headset for hybrid workers—market-leading ANC, outstanding mic clarity, and Teams/Zoom certified.",
    features: { activeNoiseCancelling: true, multiDevice: true, busyLight: true },
    specifications: { batteryLife: "37 hours", ucCertified: ["Microsoft Teams", "Zoom", "Google Meet"], connectivity: "Bluetooth 5.0 + USB dongle" },
    officialWebsite: "https://jabra.com/evolve2-85",
    documentationUrl: "https://developer.jabra.com",
    featuredImageUrl: IMG.hardware_headset,
  },
  {
    productName: "Anker 778 Thunderbolt Dock",
    productSlug: "anker-778-thunderbolt-dock",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Dock & Hub",
    manufacturer: "Anker",
    description: "Thunderbolt 4 docking station reviewed for thermal performance, failure rate history, power delivery, display output, and OS compatibility.",
    price: 249.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 87.1,
    verdictSummary: "Feature-complete Thunderbolt 4 dock with triple-display support and 140W laptop charging—solid value at the price.",
    features: { thunderbolt4: true, tripleDisplay: true, powerDelivery140W: true, ethernet2Point5G: true },
    specifications: { ports: "12 total", upstreamPowerDelivery: "140W", maxResolution: "8K or dual 4K" },
    officialWebsite: "https://anker.com/778-dock",
    documentationUrl: "https://support.anker.com",
    featuredImageUrl: IMG.hardware_dock,
  },
  {
    productName: "Herman Miller Aeron",
    productSlug: "herman-miller-aeron",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Ergonomic Chair",
    manufacturer: "Herman Miller",
    description: "Ergonomic office chair reviewed for materials durability, 12-year warranty coverage, and accessory ecosystem compatibility.",
    price: 1795.00,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 95.0,
    verdictSummary: "The benchmark ergonomic chair with a 12-year warranty, PostureFit SL lumbar support, and proven 30-year longevity.",
    features: { postureFitSL: true, eightZoneTilt: true, forwardTilt: true, adjustableArms: true },
    specifications: { warrantyYears: 12, sizesAvailable: ["A", "B", "C"], weightCapacityKg: 158 },
    officialWebsite: "https://hermanmiller.com/aeron",
    documentationUrl: "https://hermanmiller.com/support",
    featuredImageUrl: IMG.hardware_chair,
  },
  {
    productName: "Synology DS923+",
    productSlug: "synology-ds923-plus",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "NAS Storage",
    manufacturer: "Synology",
    description: "4-bay NAS device reviewed for RAID reliability, backup tooling depth, security update track record, and cloud/directory integrations.",
    price: 599.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 91.8,
    verdictSummary: "Best SMB NAS with outstanding DSM OS, Active Directory integration, and a 10GbE-ready expansion slot.",
    features: { tenGbeExpansion: true, nvmeCache: true, activeDirectoryIntegration: true, hybridBackup: true },
    specifications: { bays: 4, cpu: "AMD Ryzen R1600", maxRawStorage: "108TB", raidTypes: ["RAID 0", "1", "5", "6", "10", "SHR"] },
    officialWebsite: "https://synology.com/ds923plus",
    documentationUrl: "https://kb.synology.com",
    featuredImageUrl: IMG.hardware_nas,
  },
  {
    productName: "Neat Bar Pro",
    productSlug: "neat-bar-pro",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Conference Room",
    manufacturer: "Neat",
    description: "All-in-one conference room video bar reviewed for firmware update cadence, vendor support responsiveness, and multi-platform meeting compatibility.",
    price: 3499.00,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 90.2,
    verdictSummary: "Premium conference room bar with AI-framing, Zoom/Teams native support, and the cleanest hardware design in its class.",
    features: { aiFraming: true, zoomNative: true, teamsNative: true, contentSharing: true },
    specifications: { cameraFOV: "113°", micRange: "7 meters", displayOutput: "4K" },
    officialWebsite: "https://neat.no/neat-bar-pro",
    documentationUrl: "https://support.neat.no",
    featuredImageUrl: IMG.hardware_conference,
  },
  {
    productName: "DYMO LabelWriter 550",
    productSlug: "dymo-labelwriter-550",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Labeler",
    manufacturer: "DYMO",
    description: "Direct-thermal label printer reviewed for print reliability, consumable cost efficiency, and inventory/shipping/asset tool integrations.",
    price: 149.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 80.3,
    verdictSummary: "Fast, reliable label printer with authentic label DRM enforcement being the main concern for cost-conscious buyers.",
    features: { authenticLabelDetection: true, barcodeSupport: true, cloudPrint: true, usb: true },
    specifications: { printSpeed: "62 labels/min", resolution: "300 dpi", labelWidth: "Up to 59mm" },
    officialWebsite: "https://dymo.com/labelwriter-550",
    documentationUrl: "https://support.dymo.com",
    featuredImageUrl: IMG.hardware_label,
  },
  {
    productName: "Logitech MX Master 3S",
    productSlug: "logitech-mx-master-3s",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Keyboard & Mouse",
    manufacturer: "Logitech",
    description: "Wireless productivity mouse reviewed for button endurance, multi-device pairing, OS-level gesture integration, and workflow app compatibility.",
    price: 99.99,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 92.4,
    verdictSummary: "The definitive productivity mouse with app-specific customization, quiet clicks, and near-silent MagSpeed scrolling.",
    features: { magSpeedScroll: true, multiOSGestures: true, appSpecificProfiles: true, usbCCharging: true },
    specifications: { dpi: "200-8000", batteryLife: "70 days", connectivity: "Bluetooth + Logi Bolt USB" },
    officialWebsite: "https://logitech.com/mx-master-3s",
    documentationUrl: "https://support.logitech.com",
    featuredImageUrl: IMG.hardware_mouse,
  },
  {
    productName: "Standdesk Pro Electric Sit-Stand",
    productSlug: "standdesk-pro-electric",
    productType: "hardware",
    hub: "hybrid_office",
    category: "Office Hardware",
    subcategory: "Ergonomic Furniture",
    manufacturer: "StandDesk",
    description: "Electric height-adjustable desk reviewed for motor durability, warranty policies, memory presets reliability, and cable management ecosystem.",
    price: 599.00,
    priceCurrency: "USD",
    priceModel: "one_time",
    status: "active",
    isSponsored: false,
    sponsorDisclosed: false,
    overallScore: 82.0,
    verdictSummary: "Solid mid-market standing desk with dual-motor stability and a 10-year frame warranty—strong value against Flexispot rivals.",
    features: { dualMotor: true, fourMemoryPresets: true, antiCollision: true, cableTray: true },
    specifications: { heightRange: "27.5-47.5 inches", weightCapacityKg: 113, frameWarrantyYears: 10 },
    officialWebsite: "https://standdesk.co",
    documentationUrl: "https://standdesk.co/support",
    featuredImageUrl: IMG.hardware_desk,
  },
];

// ---------------------------------------------------------------------------
// Trust & Integration scores mapped by productSlug
// ---------------------------------------------------------------------------
interface ScoreEntry { trust: TrustSeed; integration: IntegrationSeed; }

const scores: Record<string, ScoreEntry> = {
  "focusflow-pro": {
    trust: { version: 1, totalScore: 7.2, dataPrivacyPractices: 2, encryptionStandards: 1, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 6.5, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "google-workspace-business-starter": {
    trust: { version: 1, totalScore: 6.8, dataPrivacyPractices: 1, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.2, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 1, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "notion-team-plan": {
    trust: { version: 1, totalScore: 7.5, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.8, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "github-enterprise": {
    trust: { version: 1, totalScore: 9.0, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.3, apiDocumentation: 3, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "hubspot-crm": {
    trust: { version: 1, totalScore: 7.2, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.5, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "miro-business": {
    trust: { version: 1, totalScore: 7.8, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.0, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "zapier-professional": {
    trust: { version: 1, totalScore: 7.5, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 0, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.5, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 1, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "zendesk-suite": {
    trust: { version: 1, totalScore: 8.2, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.8, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "todoist-business": {
    trust: { version: 1, totalScore: 8.5, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.5, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "grammarly-business": {
    trust: { version: 1, totalScore: 6.5, dataPrivacyPractices: 1, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.2, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "microsoft-365-business-standard": {
    trust: { version: 1, totalScore: 8.5, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.0, apiDocumentation: 3, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "make-core": {
    trust: { version: 1, totalScore: 7.6, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 0, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.7, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "clickup-business": {
    trust: { version: 1, totalScore: 7.3, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.3, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "n8n-community-edition": {
    trust: { version: 1, totalScore: 8.8, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.5, apiDocumentation: 2, crossPlatform: 2, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "atlassian-confluence-cloud": {
    trust: { version: 1, totalScore: 7.8, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.1, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "asana-business": {
    trust: { version: 1, totalScore: 8.0, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.3, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "pipedrive-crm": {
    trust: { version: 1, totalScore: 7.4, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.8, apiDocumentation: 2, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "amazon-echo-hub": {
    trust: { version: 1, totalScore: 7.2, dataPrivacyPractices: 1, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.0, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 3, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "schlage-encode-plus": {
    trust: { version: 1, totalScore: 9.0, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.5, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "arlo-pro-5s": {
    trust: { version: 1, totalScore: 8.3, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.5, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 2, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "eero-max-7": {
    trust: { version: 1, totalScore: 8.0, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.7, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "ecobee-smart-thermostat-premium": {
    trust: { version: 1, totalScore: 9.2, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.3, apiDocumentation: 2, crossPlatform: 2, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "philips-hue-starter-kit": {
    trust: { version: 1, totalScore: 8.5, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.5, apiDocumentation: 2, crossPlatform: 2, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "kasa-smart-plug-ep25": {
    trust: { version: 1, totalScore: 7.0, dataPrivacyPractices: 1, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.5, apiDocumentation: 1, crossPlatform: 1, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "roborock-s8-pro-ultra": {
    trust: { version: 1, totalScore: 7.5, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.8, apiDocumentation: 1, crossPlatform: 1, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "google-nest-doorbell-wired": {
    trust: { version: 1, totalScore: 6.8, dataPrivacyPractices: 1, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.5, apiDocumentation: 1, crossPlatform: 1, smartHomeEcosystems: 2, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "aqara-multi-sensor-kit": {
    trust: { version: 1, totalScore: 8.8, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.0, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "google-nest-thermostat": {
    trust: { version: 1, totalScore: 7.0, dataPrivacyPractices: 1, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.8, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 2, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "ring-video-doorbell-pro-2": {
    trust: { version: 1, totalScore: 5.5, dataPrivacyPractices: 1, encryptionStandards: 1, termsTransparency: 1, ethicalAiTransparency: 0, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.5, apiDocumentation: 1, crossPlatform: 1, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "tp-link-tapo-l930": {
    trust: { version: 1, totalScore: 6.8, dataPrivacyPractices: 1, encryptionStandards: 2, termsTransparency: 1, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.0, apiDocumentation: 1, crossPlatform: 1, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "lutron-caseta-smart-switch": {
    trust: { version: 1, totalScore: 9.0, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.0, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 3, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "dell-ultrasharp-u3223qe": {
    trust: { version: 1, totalScore: 8.5, dataPrivacyPractices: 3, encryptionStandards: 1, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.8, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "keychron-q1-pro": {
    trust: { version: 1, totalScore: 9.0, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.8, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "brother-mfc-l3760cdw": {
    trust: { version: 1, totalScore: 8.2, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.0, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 0, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "logitech-brio-4k": {
    trust: { version: 1, totalScore: 8.0, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.5, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "jabra-evolve2-85": {
    trust: { version: 1, totalScore: 8.7, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.0, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "anker-778-thunderbolt-dock": {
    trust: { version: 1, totalScore: 7.8, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.3, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 1, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "herman-miller-aeron": {
    trust: { version: 1, totalScore: 9.5, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 5.0, apiDocumentation: 0, crossPlatform: 1, smartHomeEcosystems: 0, automationPlatforms: 1, developerCommunity: 0, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "synology-ds923-plus": {
    trust: { version: 1, totalScore: 9.2, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.7, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "neat-bar-pro": {
    trust: { version: 1, totalScore: 8.5, dataPrivacyPractices: 2, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 9.2, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "dymo-labelwriter-550": {
    trust: { version: 1, totalScore: 6.5, dataPrivacyPractices: 1, encryptionStandards: 1, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 7.0, apiDocumentation: 1, crossPlatform: 2, smartHomeEcosystems: 0, automationPlatforms: 1, developerCommunity: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "logitech-mx-master-3s": {
    trust: { version: 1, totalScore: 8.8, dataPrivacyPractices: 3, encryptionStandards: 2, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 8.5, apiDocumentation: 1, crossPlatform: 3, smartHomeEcosystems: 0, automationPlatforms: 2, developerCommunity: 2, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
  "standdesk-pro-electric": {
    trust: { version: 1, totalScore: 8.0, dataPrivacyPractices: 3, encryptionStandards: 1, termsTransparency: 2, ethicalAiTransparency: 1, thirdPartyAudits: 1, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
    integration: { version: 1, totalScore: 4.5, apiDocumentation: 0, crossPlatform: 1, smartHomeEcosystems: 0, automationPlatforms: 1, developerCommunity: 0, testedBy: TESTER, testedDate: NOW, isCurrent: true, isVerified: true, createdBy: CREATOR },
  },
};

// ---------------------------------------------------------------------------
// Seed mutations
// ---------------------------------------------------------------------------

/**
 * Seed all competitive products and their scores.
 * Safe to run multiple times – skips slugs already in the DB.
 */
export const seedCompetitiveProducts = mutation({
  args: {},
  handler: async (ctx) => {
    let productsInserted = 0;
    let scoresInserted = 0;
    const skipped: string[] = [];

    for (const p of products) {
      const existing = await ctx.db
        .query("novaProducts")
        .withIndex("by_slug", (q) => q.eq("productSlug", p.productSlug))
        .first();

      if (existing) {
        skipped.push(p.productSlug);
        continue;
      }

      const productId = await ctx.db.insert("novaProducts", p);
      productsInserted++;

      const s = scores[p.productSlug];
      if (s) {
        await ctx.db.insert("novaTrustScores", {
          productId,
          ...s.trust,
        });
        await ctx.db.insert("novaIntegrationScores", {
          productId,
          ...s.integration,
        });
        scoresInserted += 2;
      }
    }

    return {
      productsInserted,
      scoresInserted,
      skipped: skipped.length,
      skippedSlugs: skipped,
    };
  },
});
