import { mutation } from "./_generated/server";

type ArticleSeed = {
  postTitle: string;
  postSlug: string;
  postType: "article";
  postStatus: "draft" | "published";
  hub: string;
  authorId: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  seoTitle: string;
  metaDescription: string;
  readingTimeMinutes: number;
  wordCount: number;
  readingLevel: string;
  tldrSummary: string;
  postContent: string;
  verdictText: string;
  isLivingGuide: boolean;
  publishedAt: number;
  schemaMarkup?: Record<string, unknown>;
};

const PUBLISHED_AT = 1742860800000;
const AUTHOR = "editor-synlab";

// Imported from user-provided Competitor Crusher editorial pack.
const ARTICLES: ArticleSeed[] = [
  {
    postTitle: "What Is a Smart Home Hub? Complete 2026 Guide With Privacy & Integration Scores",
    postSlug: "what-is-a-smart-home-hub-complete-guide",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "what is a smart home hub",
    secondaryKeywords: ["smart home hub explained", "smart home hub 2026"],
    seoTitle: "What Is a Smart Home Hub? Complete 2026 Guide With Privacy & Integration Scores",
    metaDescription: "Expert 2026 guide to smart home hubs, privacy, and integration scoring.",
    readingTimeMinutes: 7,
    wordCount: 950,
    readingLevel: "beginner",
    tldrSummary: "A smart home hub is the brain connecting device ecosystems with local automation and better privacy.",
    postContent: "A smart home hub centralizes control, bridges protocols like Zigbee/Z-Wave/Matter, and runs automations locally for faster and more private operation.",
    verdictText: "A smart home hub improves reliability, privacy, and cross-brand integration.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Do You Need a Smart Home Hub in 2026? Honest Answer for Every Type of User",
    postSlug: "do-you-need-a-smart-home-hub-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "do you need a smart home hub",
    secondaryKeywords: ["smart home hub worth it", "smart home without hub"],
    seoTitle: "Do You Need a Smart Home Hub in 2026? Honest Answer for Every Setup",
    metaDescription: "When a hub is optional and when it becomes essential in 2026.",
    readingTimeMinutes: 7,
    wordCount: 930,
    readingLevel: "beginner",
    tldrSummary: "Single-ecosystem users often do not need one yet; mixed-brand and privacy-first users do.",
    postContent: "Hub need depends on device count, protocol mix, cloud dependency tolerance, and privacy requirements.",
    verdictText: "Mixed-brand, 10+ device users benefit significantly from dedicated hubs.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "How Does a Smart Home Hub Work? The Technical Truth, Simply Explained",
    postSlug: "how-does-a-smart-home-hub-work",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "how does a smart home hub work",
    secondaryKeywords: ["smart home hub protocols", "local vs cloud smart home"],
    seoTitle: "How Does a Smart Home Hub Work? Protocols, Automations & Local Control Explained",
    metaDescription: "Technical breakdown of hub radios, meshes, and automation engines.",
    readingTimeMinutes: 7,
    wordCount: 940,
    readingLevel: "intermediate",
    tldrSummary: "Hubs host multiple radios and run automation engines to coordinate devices locally.",
    postContent: "A hub receives protocol packets, evaluates rule logic, and triggers actions locally with lower latency.",
    verdictText: "Hubs bridge incompatible protocols and provide local automation reliability.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Best Smart Home Hub for HomeKit in 2026: Ranked by Integration Score",
    postSlug: "best-smart-home-hub-for-homekit-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "best smart home hub for HomeKit",
    secondaryKeywords: ["HomeKit hub 2026", "HomePod vs Apple TV hub"],
    seoTitle: "Best Smart Home Hub for HomeKit 2026: Ranked by Integration & Trust Score",
    metaDescription: "HomeKit hub rankings by Integration and Trust scores.",
    readingTimeMinutes: 7,
    wordCount: 920,
    readingLevel: "intermediate",
    tldrSummary: "HomePod (2nd gen) leads native HomeKit, while HomeBridge boosts protocol breadth.",
    postContent: "HomeKit hubs vary by Thread support, automation depth, and ecosystem lock-in trade-offs.",
    verdictText: "HomePod 2nd gen leads native HomeKit; HomeBridge best for expanding compatibility.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Best Smart Home Hub for Alexa in 2026: Ranked by Integration Score",
    postSlug: "best-smart-home-hub-for-alexa-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "best smart home hub for Alexa",
    secondaryKeywords: ["Alexa smart home hub 2026", "Alexa Zigbee hub"],
    seoTitle: "Best Smart Home Hub for Alexa 2026: Integration Scores, Protocols & Privacy",
    metaDescription: "Alexa-compatible hub rankings and privacy trade-offs in 2026.",
    readingTimeMinutes: 7,
    wordCount: 920,
    readingLevel: "intermediate",
    tldrSummary: "Echo is easiest native option; Hubitat/Home Assistant improve local reliability.",
    postContent: "Alexa works best with dedicated local hubs for mission-critical automations and mixed-protocol stacks.",
    verdictText: "Echo for simplicity; Hubitat/Home Assistant for performance and privacy.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Best Smart Home Hub for Google Home in 2026: Integration Score Rankings",
    postSlug: "best-smart-home-hub-for-google-home-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "best smart home hub for Google Home",
    secondaryKeywords: ["Google Home hub 2026", "Nest Hub Thread border router"],
    seoTitle: "Best Smart Home Hub for Google Home 2026: Ranked by Integration & Trust Score",
    metaDescription: "Google Home hub rankings for Matter, Thread, and automation depth.",
    readingTimeMinutes: 7,
    wordCount: 915,
    readingLevel: "intermediate",
    tldrSummary: "Nest Hub Max leads native options; Home Assistant leads maximum breadth.",
    postContent: "Google Home has improved Matter support, but dedicated local hubs still lead on reliability.",
    verdictText: "Nest Hub Max for native simplicity; Home Assistant for advanced integrations.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Best Smart Home Hub for Privacy in 2026: Ranked by Trust Score",
    postSlug: "best-smart-home-hub-for-privacy-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "best smart home hub for privacy",
    secondaryKeywords: ["privacy smart home hub 2026", "smart home no cloud"],
    seoTitle: "Best Smart Home Hub for Privacy 2026: Ranked by Trust Score & Local Control",
    metaDescription: "Privacy-first smart home hub ranking and trust methodology.",
    readingTimeMinutes: 7,
    wordCount: 935,
    readingLevel: "intermediate",
    tldrSummary: "Home Assistant self-hosted tops Trust Score; Hubitat best commercial local option.",
    postContent: "Privacy depends on local processing, telemetry minimization, encryption, audits, and policy transparency.",
    verdictText: "Home Assistant and Hubitat lead privacy-first hub recommendations.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub vs Smart Speaker: What's Actually the Difference in 2026?",
    postSlug: "smart-home-hub-vs-smart-speaker-difference",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub vs smart speaker",
    secondaryKeywords: ["do smart speakers work as hubs", "Echo vs smart home hub"],
    seoTitle: "Smart Home Hub vs Smart Speaker: What's the Real Difference in 2026?",
    metaDescription: "Clear explanation of hub brains vs speaker assistants and overlap devices.",
    readingTimeMinutes: 6,
    wordCount: 900,
    readingLevel: "beginner",
    tldrSummary: "Speakers are voice/audio-first; hubs are protocol/automation-first.",
    postContent: "Hybrid devices can do both, but dedicated hubs still outperform for complex automation and protocol breadth.",
    verdictText: "Use smart speakers for voice, dedicated hubs for reliability and deep integration.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub Setup Guide 2026: Step-by-Step for Beginners",
    postSlug: "smart-home-hub-setup-guide-beginners-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub setup",
    secondaryKeywords: ["how to set up smart home hub", "smart home hub beginner guide"],
    seoTitle: "Smart Home Hub Setup Guide 2026: Step-by-Step for Every Major Platform",
    metaDescription: "Beginner setup guide for Echo, HomePod, Hubitat, and Home Assistant.",
    readingTimeMinutes: 7,
    wordCount: 920,
    readingLevel: "beginner",
    tldrSummary: "Place centrally, use Ethernet, pair by protocol, and start with simple automations.",
    postContent: "A reliable setup flow includes placement, protocol-first pairing, and validation with logs and backup.",
    verdictText: "Correct placement + protocol-first onboarding avoids most early hub failures.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub Protocols Explained: Zigbee vs Z-Wave vs Matter vs Thread in 2026",
    postSlug: "smart-home-hub-protocols-zigbee-zwave-matter-thread",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub protocols",
    secondaryKeywords: ["Zigbee vs Z-Wave vs Matter 2026", "Thread protocol smart home"],
    seoTitle: "Smart Home Hub Protocols in 2026: Zigbee vs Z-Wave vs Matter vs Thread Explained",
    metaDescription: "Protocol comparison and when each one matters for hub selection.",
    readingTimeMinutes: 7,
    wordCount: 930,
    readingLevel: "intermediate",
    tldrSummary: "Best hubs speak all major protocols and expose strong local automation.",
    postContent: "Each protocol has trade-offs in range, power, security, and ecosystem size; hub breadth matters most.",
    verdictText: "Protocol-complete hubs offer long-term flexibility and better integration scores.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "5 Best Smart Home Hubs for Beginners in 2026 -- Ranked and Scored",
    postSlug: "best-smart-home-hubs-for-beginners-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "best smart home hub for beginners",
    secondaryKeywords: ["easiest smart home hub 2026", "best starter smart home hub"],
    seoTitle: "5 Best Smart Home Hubs for Beginners 2026: Easy Setup, Ranked by Score",
    metaDescription: "Beginner-friendly hub rankings with setup complexity and trade-offs.",
    readingTimeMinutes: 7,
    wordCount: 920,
    readingLevel: "beginner",
    tldrSummary: "HomePod mini, Echo, and Nest Hub are easiest; Hubitat best growth path.",
    postContent: "Beginner ranking balances setup simplicity, integration breadth, and trust score.",
    verdictText: "Choose by ecosystem now and expected complexity growth later.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub Not Working? 10 Fixes That Actually Solve It in 2026",
    postSlug: "smart-home-hub-not-working-troubleshooting-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub not working",
    secondaryKeywords: ["smart home hub troubleshooting", "smart home hub offline"],
    seoTitle: "Smart Home Hub Not Working? 10 Proven Fixes for Every Platform (2026)",
    metaDescription: "High-success troubleshooting checklist for hub reliability issues.",
    readingTimeMinutes: 6,
    wordCount: 905,
    readingLevel: "intermediate",
    tldrSummary: "Most failures are power order, RF interference, mesh repair, or cloud dependency.",
    postContent: "Troubleshooting sequence: power cycle, firmware, channels, mesh rebuild, DHCP, cloud status, loops, and backups.",
    verdictText: "A disciplined troubleshooting order resolves most failures quickly.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub Comparison 2026: Hubitat vs Home Assistant vs SmartThings",
    postSlug: "smart-home-hub-comparison-hubitat-home-assistant-smartthings",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub comparison",
    secondaryKeywords: ["Hubitat vs Home Assistant 2026", "Hubitat vs SmartThings"],
    seoTitle: "Hubitat vs Home Assistant vs SmartThings 2026: Integration Score Comparison",
    metaDescription: "Head-to-head dedicated hub comparison by scoring and lab behavior.",
    readingTimeMinutes: 7,
    wordCount: 930,
    readingLevel: "intermediate",
    tldrSummary: "Home Assistant leads maximum flexibility; Hubitat is best commercial local hub.",
    postContent: "Comparison focuses on local reliability, protocol breadth, update cadence, and cloud dependence.",
    verdictText: "Pick HA for ceiling, Hubitat for simplicity, SmartThings for Samsung-centric ease.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home on a Budget: Best Cheap Smart Home Hubs Under $100 in 2026",
    postSlug: "best-cheap-smart-home-hub-under-100-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "best cheap smart home hub",
    secondaryKeywords: ["smart home hub under $100", "budget smart home hub 2026"],
    seoTitle: "Best Cheap Smart Home Hubs Under $100 in 2026: Ranked by Value Score",
    metaDescription: "Budget hub rankings under $100 with value and trade-off analysis.",
    readingTimeMinutes: 6,
    wordCount: 905,
    readingLevel: "beginner",
    tldrSummary: "DIY Home Assistant is highest long-term value; HomePod mini leads privacy in this tier.",
    postContent: "Under $100 options vary by protocol support and cloud dependence; choose by growth plans.",
    verdictText: "Price alone is not value; protocol breadth and local control matter.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub for Renters in 2026: No Hardwiring, Full Control",
    postSlug: "smart-home-hub-for-renters-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub for renters",
    secondaryKeywords: ["renter smart home 2026", "portable smart home hub"],
    seoTitle: "Smart Home Hub for Renters 2026: Build It, Pack It, Take It With You",
    metaDescription: "Portable renter-friendly smart home hub and device strategy.",
    readingTimeMinutes: 6,
    wordCount: 905,
    readingLevel: "beginner",
    tldrSummary: "Use reversible, portable setups with plug-in devices and mesh-friendly sensors.",
    postContent: "Renters should optimize for portability, reversible installs, and fast move/re-pair workflows.",
    verdictText: "A fully capable renter-friendly smart home is practical in 2026.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub Energy Monitoring in 2026: Which Hubs Track Your Consumption?",
    postSlug: "smart-home-hub-energy-monitoring-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub energy monitoring",
    secondaryKeywords: ["smart home energy management hub", "Home Assistant energy dashboard"],
    seoTitle: "Smart Home Hub Energy Monitoring 2026: Which Hubs Track and Optimize Your Usage",
    metaDescription: "Energy monitoring depth comparison across major smart home hubs.",
    readingTimeMinutes: 6,
    wordCount: 910,
    readingLevel: "intermediate",
    tldrSummary: "Home Assistant leads with native dashboards and energy-triggered automations.",
    postContent: "Energy optimization requires whole-home + device-level telemetry and an automation engine to act on it.",
    verdictText: "Hub choice directly affects measurable energy savings potential.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Best Smart Home Hub for Security in 2026: Alarms, Locks, and Cameras Integrated",
    postSlug: "best-smart-home-hub-for-security-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "best smart home hub for security",
    secondaryKeywords: ["smart home security hub 2026", "Z-Wave security smart home"],
    seoTitle: "Best Smart Home Hub for Security 2026: Alarms, Locks & Cameras Ranked",
    metaDescription: "Security-focused hub ranking by local processing and protocol security.",
    readingTimeMinutes: 7,
    wordCount: 925,
    readingLevel: "intermediate",
    tldrSummary: "Security requires local processing, strong lock protocol support, and high trust score.",
    postContent: "For security workflows, local automation and robust protocol security are non-negotiable.",
    verdictText: "Home Assistant and Hubitat remain top security-first choices.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub Future: What Matter 1.4 and Thread 1.4 Mean for Your Hub in 2026",
    postSlug: "smart-home-hub-future-matter-thread-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub future 2026",
    secondaryKeywords: ["Matter 1.4 2026", "Thread 1.4 smart home"],
    seoTitle: "The Future of Smart Home Hubs in 2026: Matter 1.4, Thread 1.4, and What's Coming",
    metaDescription: "Protocol roadmap impact on hub longevity and scoring.",
    readingTimeMinutes: 6,
    wordCount: 900,
    readingLevel: "intermediate",
    tldrSummary: "Update cadence and software-defined protocol stacks decide long-term hub value.",
    postContent: "Future-proofing depends on vendor update commitments for Matter/Thread revisions.",
    verdictText: "Choose hubs with reliable protocol update delivery over static hardware claims.",
    isLivingGuide: true,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub Integration Score Explained: How TheSynLab Rates Every Hub",
    postSlug: "smart-home-hub-integration-score-explained",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub integration score",
    secondaryKeywords: ["TheSynLab Integration Score", "smart home hub review methodology"],
    seoTitle: "TheSynLab Integration Score for Smart Home Hubs: Full Methodology Explained",
    metaDescription: "Complete scoring methodology for Integration Score calculations.",
    readingTimeMinutes: 6,
    wordCount: 905,
    readingLevel: "intermediate",
    tldrSummary: "Integration Score blends protocol breadth, APIs, automation compatibility, community, and reliability.",
    postContent: "Methodology transparency enables objective product comparisons and quarterly score updates.",
    verdictText: "Integration Score is a weighted, evidence-based benchmark—not a marketing label.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub vs Router: Can Your Router Replace a Hub in 2026?",
    postSlug: "smart-home-hub-vs-router-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub vs router",
    secondaryKeywords: ["router with smart home hub", "can router replace smart home hub"],
    seoTitle: "Smart Home Hub vs Router in 2026: Can Your Router Replace a Hub?",
    metaDescription: "When router-native Matter/Thread is enough and when dedicated hubs still win.",
    readingTimeMinutes: 6,
    wordCount: 910,
    readingLevel: "intermediate",
    tldrSummary: "Routers can cover simple Matter use-cases but not deep automation and full protocol breadth.",
    postContent: "Router and hub roles overlap in 2026, but dedicated hubs remain superior for complex orchestration.",
    verdictText: "Use routers for networking and hubs for automation intelligence.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
  },
  {
    postTitle: "Smart Home Hub for Home Office in 2026: Automate Your Productivity Space",
    postSlug: "smart-home-hub-home-office-2026",
    postType: "article",
    postStatus: "draft",
    hub: "smart-home",
    authorId: AUTHOR,
    primaryKeyword: "smart home hub home office",
    secondaryKeywords: ["smart office automation 2026", "automate home office hub"],
    seoTitle: "Smart Home Hub for Home Office 2026: Automate Lighting, Climate & Focus Mode",
    metaDescription: "Home office automation stack design with productivity and energy outcomes.",
    readingTimeMinutes: 6,
    wordCount: 905,
    readingLevel: "intermediate",
    tldrSummary: "Calendar-aware and presence-based automation can materially improve focus and comfort.",
    postContent: "Home office automations should combine lighting, climate, occupancy, and meeting-state signals.",
    verdictText: "Home office is one of the highest-ROI smart home automation verticals.",
    isLivingGuide: false,
    publishedAt: PUBLISHED_AT,
    schemaMarkup: {
      "@context": "https://schema.org",
      "@type": "TechArticle",
      headline: "Smart Home Hub for Home Office in 2026: Automate Your Productivity Space",
    },
  },
];

export const seedSmartHomeArticles = mutation({
  args: {},
  handler: async (ctx) => {
    let created = 0;
    let updated = 0;
    let livingGuidesCreated = 0;
    let livingGuidesUpdated = 0;

    for (const article of ARTICLES) {
      const existing = await ctx.db
        .query("novaPosts")
        .withIndex("by_slug", (q) => q.eq("postSlug", article.postSlug))
        .first();

      const patch = {
        ...article,
        viewCount: existing?.viewCount ?? 0,
        uniqueViewCount: existing?.uniqueViewCount ?? 0,
      };

      let postId = existing?._id;
      if (existing) {
        await ctx.db.patch(existing._id, patch);
        updated++;
      } else {
        postId = await ctx.db.insert("novaPosts", patch);
        created++;
      }

      if (postId && article.isLivingGuide) {
        const existingGuide = await ctx.db
          .query("livingGuides")
          .withIndex("by_post", (q) => q.eq("postId", postId!))
          .first();
        const now = Date.now();
        const nextReviewDue = now + 1000 * 60 * 60 * 24 * 90;

        if (existingGuide) {
          await ctx.db.patch(existingGuide._id, {
            isLivingGuide: true,
            lastReviewedAt: now,
            nextReviewDue,
            updateFrequency: "quarterly",
          });
          livingGuidesUpdated++;
        } else {
          await ctx.db.insert("livingGuides", {
            postId,
            updateFrequency: "quarterly",
            lastReviewedAt: now,
            nextReviewDue,
            isLivingGuide: true,
            changeLog: [
              { at: now, change: "Initial living guide link created by smart-home article seed." },
            ],
          });
          livingGuidesCreated++;
        }
      }
    }

    return {
      totalInput: ARTICLES.length,
      created,
      updated,
      livingGuidesCreated,
      livingGuidesUpdated,
    };
  },
});

